import { Pool } from 'pg';
import type { DirectoryStore } from '../application/DirectoryService.js';
import type { AccountTokenPurpose, AuditEvent, DirectoryAccount, DirectoryAccountToken, DirectoryEdgeConnection, DirectoryPairingCode, DirectoryHome, DirectoryHomeMembership, MembershipStatus } from '../domain/entities.js';

export class PostgresDirectoryDatabase implements DirectoryStore {
  private readonly pool: Pool;
  constructor(connectionString: string) { this.pool = new Pool({ connectionString }); }
  async migrate(): Promise<void> {
    await this.pool.query(`
      CREATE TABLE IF NOT EXISTS directory_accounts (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, display_name TEXT NOT NULL, email_verified BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL);
      CREATE TABLE IF NOT EXISTS directory_homes (id TEXT PRIMARY KEY, name TEXT NOT NULL, edge_hostname TEXT NOT NULL, owner_account_id TEXT NOT NULL REFERENCES directory_accounts(id), created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
      CREATE TABLE IF NOT EXISTS directory_home_memberships (id TEXT PRIMARY KEY, home_id TEXT NOT NULL REFERENCES directory_homes(id) ON DELETE CASCADE, account_id TEXT NOT NULL REFERENCES directory_accounts(id), role TEXT NOT NULL CHECK(role IN ('owner','member')), status TEXT NOT NULL CHECK(status IN ('pending','active','revoked')), invited_by_account_id TEXT REFERENCES directory_accounts(id), invitation_token_hash TEXT UNIQUE, invitation_expires_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, UNIQUE(home_id, account_id));
      CREATE INDEX IF NOT EXISTS idx_memberships_account_active ON directory_home_memberships(account_id, status);
      CREATE TABLE IF NOT EXISTS directory_audit_events (id TEXT PRIMARY KEY, actor_account_id TEXT NOT NULL, home_id TEXT, membership_id TEXT, action TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL);
      CREATE INDEX IF NOT EXISTS idx_audit_home_created ON directory_audit_events(home_id, created_at DESC); CREATE TABLE IF NOT EXISTS directory_account_tokens (id TEXT PRIMARY KEY, account_id TEXT NOT NULL REFERENCES directory_accounts(id) ON DELETE CASCADE, purpose TEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, used_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL); ALTER TABLE directory_accounts ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE; CREATE TABLE IF NOT EXISTS directory_edge_connections (id TEXT PRIMARY KEY, home_id TEXT NOT NULL REFERENCES directory_homes(id) ON DELETE CASCADE, edge_id TEXT NOT NULL UNIQUE, credential_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ); CREATE TABLE IF NOT EXISTS directory_pairing_codes (id TEXT PRIMARY KEY, home_id TEXT NOT NULL REFERENCES directory_homes(id) ON DELETE CASCADE, code_hash TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, used_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL);
    `);
  }
  async createAccount(value: DirectoryAccount): Promise<void> { await this.pool.query("INSERT INTO directory_accounts (id,email,password_hash,display_name,email_verified,created_at) VALUES ($1,$2,$3,$4,$5,$6)", [value.id, value.email, value.passwordHash, value.displayName, value.emailVerified, value.createdAt]); }
  async findAccountByEmail(email: string): Promise<DirectoryAccount | null> { return mapAccount((await this.pool.query("SELECT * FROM directory_accounts WHERE email=$1", [email])).rows[0]); }
  async findAccountById(id: string): Promise<DirectoryAccount | null> { return mapAccount((await this.pool.query("SELECT * FROM directory_accounts WHERE id=$1", [id])).rows[0]); }
  async updateAccount(value: DirectoryAccount): Promise<void> { await this.pool.query("UPDATE directory_accounts SET password_hash=$1,display_name=$2,email_verified=$3 WHERE id=$4", [value.passwordHash, value.displayName, value.emailVerified, value.id]); }
  async createAccountToken(value: DirectoryAccountToken): Promise<void> { await this.pool.query("INSERT INTO directory_account_tokens (id,account_id,purpose,token_hash,expires_at,used_at,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7)", [value.id, value.accountId, value.purpose, value.tokenHash, value.expiresAt, value.usedAt, value.createdAt]); }
  async findAccountTokenByHash(hash: string): Promise<DirectoryAccountToken | null> { const row = (await this.pool.query("SELECT * FROM directory_account_tokens WHERE token_hash=$1", [hash])).rows[0] as Row | undefined; return row ? { id: String(row.id), accountId: String(row.account_id), purpose: String(row.purpose) as AccountTokenPurpose, tokenHash: String(row.token_hash), expiresAt: iso(row.expires_at), usedAt: row.used_at ? iso(row.used_at) : null, createdAt: iso(row.created_at) } : null; }
  async consumeAccountToken(id: string, now: string): Promise<boolean> { return (await this.pool.query("UPDATE directory_account_tokens SET used_at=$1 WHERE id=$2 AND used_at IS NULL AND expires_at>$1", [now, id])).rowCount === 1; }
  async createHome(value: DirectoryHome): Promise<void> { await this.pool.query('INSERT INTO directory_homes (id,name,edge_hostname,owner_account_id,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6)',[value.id,value.name,value.edgeHostname,value.ownerAccountId,value.createdAt,value.updatedAt]); }
  async findHomeById(id: string): Promise<DirectoryHome | null> { return mapHome((await this.pool.query('SELECT * FROM directory_homes WHERE id=$1',[id])).rows[0]); }
  async updateHome(value: DirectoryHome): Promise<void> { await this.pool.query('UPDATE directory_homes SET name=$1,edge_hostname=$2,owner_account_id=$3,updated_at=$4 WHERE id=$5',[value.name,value.edgeHostname,value.ownerAccountId,value.updatedAt,value.id]); }
  async deleteById(id: string): Promise<void> { await this.pool.query('DELETE FROM directory_homes WHERE id=$1',[id]); }
  async createMembership(value: DirectoryHomeMembership): Promise<void> { await this.pool.query('INSERT INTO directory_home_memberships (id,home_id,account_id,role,status,invited_by_account_id,invitation_token_hash,invitation_expires_at,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[value.id,value.homeId,value.accountId,value.role,value.status,value.invitedByAccountId,value.invitationTokenHash,value.invitationExpiresAt,value.createdAt,value.updatedAt]); }
  async findByHomeAndAccount(homeId:string,accountId:string):Promise<DirectoryHomeMembership|null>{return mapMembership((await this.pool.query('SELECT * FROM directory_home_memberships WHERE home_id=$1 AND account_id=$2',[homeId,accountId])).rows[0]);}
  async findByInvitationTokenHash(hash:string):Promise<DirectoryHomeMembership|null>{return mapMembership((await this.pool.query('SELECT * FROM directory_home_memberships WHERE invitation_token_hash=$1',[hash])).rows[0]);}
  async listByHome(homeId:string):Promise<DirectoryHomeMembership[]>{return (await this.pool.query('SELECT * FROM directory_home_memberships WHERE home_id=$1 ORDER BY created_at',[homeId])).rows.map(mapMembershipRequired);}
  async listActiveHomesForAccount(accountId:string):Promise<Array<{home:DirectoryHome;membership:DirectoryHomeMembership}>>{const rows=(await this.pool.query(`SELECT h.id AS h_id,h.name AS h_name,h.edge_hostname AS h_edge_hostname,h.owner_account_id AS h_owner_account_id,h.created_at AS h_created_at,h.updated_at AS h_updated_at,m.id AS m_id,m.home_id AS m_home_id,m.account_id AS m_account_id,m.role AS m_role,m.status AS m_status,m.invited_by_account_id AS m_invited_by_account_id,m.invitation_token_hash AS m_invitation_token_hash,m.invitation_expires_at AS m_invitation_expires_at,m.created_at AS m_created_at,m.updated_at AS m_updated_at FROM directory_home_memberships m JOIN directory_homes h ON h.id=m.home_id WHERE m.account_id=$1 AND m.status='active' ORDER BY h.name`,[accountId])).rows;return rows.map(row=>({home:{id:row.h_id,name:row.h_name,edgeHostname:row.h_edge_hostname,ownerAccountId:row.h_owner_account_id,createdAt:iso(row.h_created_at),updatedAt:iso(row.h_updated_at)},membership:{id:row.m_id,homeId:row.m_home_id,accountId:row.m_account_id,role:row.m_role,status:row.m_status,invitedByAccountId:row.m_invited_by_account_id,invitationTokenHash:row.m_invitation_token_hash,invitationExpiresAt:row.m_invitation_expires_at?iso(row.m_invitation_expires_at):null,createdAt:iso(row.m_created_at),updatedAt:iso(row.m_updated_at)}}));}
  async updateMembership(value:DirectoryHomeMembership):Promise<void>{await this.pool.query('UPDATE directory_home_memberships SET role=$1,status=$2,invited_by_account_id=$3,invitation_token_hash=$4,invitation_expires_at=$5,updated_at=$6 WHERE id=$7',[value.role,value.status,value.invitedByAccountId,value.invitationTokenHash,value.invitationExpiresAt,value.updatedAt,value.id]);}
  async createEdgeConnection(value: DirectoryEdgeConnection): Promise<void> { await this.pool.query('INSERT INTO directory_edge_connections (id,home_id,edge_id,credential_hash,created_at,revoked_at) VALUES ($1,$2,$3,$4,$5,$6)',[value.id,value.homeId,value.edgeId,value.credentialHash,value.createdAt,value.revokedAt]); }
  async findActiveByHomeId(homeId: string): Promise<DirectoryEdgeConnection | null> { return mapEdgeConnection((await this.pool.query('SELECT * FROM directory_edge_connections WHERE home_id=$1 AND revoked_at IS NULL',[homeId])).rows[0]); }
  async findActiveByEdgeId(edgeId: string): Promise<DirectoryEdgeConnection | null> { return mapEdgeConnection((await this.pool.query('SELECT * FROM directory_edge_connections WHERE edge_id=$1 AND revoked_at IS NULL',[edgeId])).rows[0]); }
  async revoke(id: string, revokedAt: string): Promise<boolean> { return (await this.pool.query('UPDATE directory_edge_connections SET revoked_at=$1 WHERE id=$2 AND revoked_at IS NULL',[revokedAt,id])).rowCount===1; }
  async invalidatePairingCodes(homeId:string,now:string):Promise<void>{await this.pool.query('UPDATE directory_pairing_codes SET used_at=$1 WHERE home_id=$2 AND used_at IS NULL',[now,homeId]);}
  async createPairingCode(value:DirectoryPairingCode):Promise<void>{await this.pool.query('INSERT INTO directory_pairing_codes (id,home_id,code_hash,expires_at,used_at,created_at) VALUES ($1,$2,$3,$4,$5,$6)',[value.id,value.homeId,value.codeHash,value.expiresAt,value.usedAt,value.createdAt]);}
  async claimPairingCode(hash:string,now:string,connection:DirectoryEdgeConnection):Promise<'claimed'|'invalid'|'used'|'expired'>{const client=await this.pool.connect();try{await client.query('BEGIN');const row=(await client.query('SELECT * FROM directory_pairing_codes WHERE code_hash=$1 FOR UPDATE',[hash])).rows[0];if(!row){await client.query('ROLLBACK');return 'invalid';}if(row.used_at){await client.query('ROLLBACK');return 'used';}if(Date.parse(row.expires_at)<=Date.parse(now)){await client.query('ROLLBACK');return 'expired';}await client.query('UPDATE directory_pairing_codes SET used_at=$1 WHERE code_hash=$2',[now,hash]);connection.homeId=String(row.home_id);await client.query('UPDATE directory_edge_connections SET revoked_at=$1 WHERE home_id=$2 AND revoked_at IS NULL',[now,connection.homeId]);await client.query('INSERT INTO directory_edge_connections (id,home_id,edge_id,credential_hash,created_at,revoked_at) VALUES ($1,$2,$3,$4,$5,$6)',[connection.id,connection.homeId,connection.edgeId,connection.credentialHash,connection.createdAt,null]);await client.query('COMMIT');return 'claimed';}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
    async append(value:AuditEvent):Promise<void>{await this.pool.query('INSERT INTO directory_audit_events (id,actor_account_id,home_id,membership_id,action,created_at) VALUES ($1,$2,$3,$4,$5,$6)',[value.id,value.actorAccountId,value.homeId,value.membershipId,value.action,value.createdAt]);}
  async listForHome(homeId:string):Promise<AuditEvent[]>{return (await this.pool.query('SELECT * FROM directory_audit_events WHERE home_id=$1 ORDER BY created_at DESC',[homeId])).rows.map(row=>({id:row.id,actorAccountId:row.actor_account_id,homeId:row.home_id,membershipId:row.membership_id,action:row.action,createdAt:iso(row.created_at)}));}
  async close():Promise<void>{await this.pool.end();}
}
type Row=Record<string,unknown>;
const iso=(value:unknown):string=>value instanceof Date?value.toISOString():String(value);
const mapEdgeConnection=(row:Row|undefined):DirectoryEdgeConnection|null=>row?{id:String(row.id),homeId:String(row.home_id),edgeId:String(row.edge_id),credentialHash:String(row.credential_hash),createdAt:iso(row.created_at),revokedAt:row.revoked_at===null?null:iso(row.revoked_at)}:null;
const mapAccount=(row:Row|undefined):DirectoryAccount|null=>row?{id:String(row.id),email:String(row.email),passwordHash:String(row.password_hash),displayName:String(row.display_name),emailVerified:Boolean(row.email_verified),createdAt:iso(row.created_at)}:null;
const mapHome=(row:Row|undefined):DirectoryHome|null=>row?{id:String(row.id),name:String(row.name),edgeHostname:String(row.edge_hostname),ownerAccountId:String(row.owner_account_id),createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)}:null;
const mapMembership=(row:Row|undefined):DirectoryHomeMembership|null=>row?mapMembershipRequired(row):null;
const mapMembershipRequired=(row:Row):DirectoryHomeMembership=>({id:String(row.id),homeId:String(row.home_id),accountId:String(row.account_id),role:String(row.role) as 'owner'|'member',status:String(row.status) as MembershipStatus,invitedByAccountId:row.invited_by_account_id===null?null:String(row.invited_by_account_id),invitationTokenHash:row.invitation_token_hash===null?null:String(row.invitation_token_hash),invitationExpiresAt:row.invitation_expires_at===null?null:iso(row.invitation_expires_at),createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)});
