const state={token:localStorage.getItem('directory_token'),homes:[],selectedHome:null};
const q=(selector)=>document.querySelector(selector); const notice=(message)=>q('#notice').textContent=message;
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'content-type':'application/json',...(state.token?{authorization:`Bearer ${state.token}`}:{})}});if(response.status===204)return null;const body=await response.json();if(!response.ok)throw new Error(body.error||'REQUEST_FAILED');return body;}
function setTab(tab){q('#login').hidden=tab!=='login';q('#register').hidden=tab!=='register';document.querySelectorAll('[data-tab]').forEach(button=>button.classList.toggle('active',button.dataset.tab===tab));}
async function loadHomes(){state.homes=await api('/directory/homes');q('#auth').hidden=true;q('#homes').hidden=false;q('#logout').hidden=false;const list=q('#home-list');list.innerHTML='';if(!state.homes.length){list.innerHTML='<p>Aún no tienes casas registradas.</p>';return;}for(const home of state.homes){const article=document.createElement('article');article.className='home-card';article.innerHTML=`<div><h2>${escapeHtml(home.name)}</h2><p>${escapeHtml(home.edgeHostname)}</p><small>${home.role==='owner'?'Propietario':'Miembro'}</small></div><button>Entrar</button>`;article.querySelector('button').onclick=()=>window.location.assign(home.edgeHostname);article.querySelector('div').onclick=()=>selectHome(home);list.append(article);}}
async function selectHome(home){state.selectedHome=home;q('#owner-panel').hidden=home.role!=='owner';q('#invite-result').textContent='';if(home.role!=='owner')return;const members=await api(`/directory/homes/${home.id}/memberships`);const list=q('#member-list');list.innerHTML=members.map(member=>`<div class="member"><span>${escapeHtml(member.displayName)} · ${escapeHtml(member.email)} · ${member.status}</span>${member.role==='member'&&member.status!=='revoked'?`<button data-account="${member.accountId}">Revocar</button>`:''}</div>`).join('');list.querySelectorAll('button[data-account]').forEach(button=>button.onclick=async()=>{try{await api(`/directory/homes/${home.id}/memberships/${button.dataset.account}`,{method:'DELETE'});await selectHome(home);notice('Acceso revocado.');}catch(error){notice(error.message);}});}
q('#login').onsubmit=async(event)=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));try{const result=await api('/directory/session',{method:'POST',body:JSON.stringify(data)});state.token=result.token;localStorage.setItem('directory_token',result.token);await loadHomes();}catch(error){notice(error.message);}};
q('#register').onsubmit=async(event)=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));try{await api('/directory/accounts',{method:'POST',body:JSON.stringify(data)});setTab('login');notice('Cuenta creada. Ahora inicia sesión.');}catch(error){notice(error.message);}};
q('#new-home').onclick=()=>q('#home-form').hidden=!q('#home-form').hidden;
q('#home-form').onsubmit=async(event)=>{event.preventDefault();try{await api('/directory/homes',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});event.currentTarget.reset();event.currentTarget.hidden=true;await loadHomes();notice('Casa registrada.');}catch(error){notice(error.message);}};
async function respondToInvitation(decision) {
  const form=q('#invitation-response'); const token=new FormData(form).get('token');
  if(typeof token!=='string'||!token) return;
  try { await api(/directory/invitations//,{method:'POST'}); form.reset(); await loadHomes(); notice(decision==='accept'?'Invitación aceptada.':'Invitación rechazada.'); } catch(error) { notice(error.message); }
}
q('#invitation-response').onsubmit=async(event)=>{event.preventDefault();await respondToInvitation('accept');};
q('#reject-invitation').onclick=()=>respondToInvitation('reject');
q('#invite-form').onsubmit=async(event)=>{event.preventDefault();if(!state.selectedHome)return;try{const invitation=await api(`/directory/homes/${state.selectedHome.id}/invitations`,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});q('#invite-result').textContent=`Invitación creada. Token para entregar de forma segura: ${invitation.token}`;event.currentTarget.reset();await selectHome(state.selectedHome);}catch(error){notice(error.message);}};
q('#logout').onclick=()=>{localStorage.removeItem('directory_token');state.token=null;state.selectedHome=null;q('#homes').hidden=true;q('#auth').hidden=false;q('#logout').hidden=true;};document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>setTab(button.dataset.tab));
const escapeHtml=(value)=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
if(state.token)loadHomes().catch(()=>q('#logout').click());
